image: Visual Studio 2017

services:
- iis

init:
- ps: Get-PackageProvider -Name NuGet -ForceBootstrap > $null
- ps: Install-Module -Name PSTestWinibleZ -Force

build: false

test_script:
- cmd: powershell.exe "Import-Module -Name PSTestWinibleZ; $res = Test-AnsibleRole; exit ([int](-not $res))"

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
